# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.proto.booking_pb2 as booking__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBooking = channel.unary_unary(
                '/booking.BookingService/CreateBooking',
                request_serializer=booking__pb2.CreateBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.Booking.FromString,
                _registered_method=True)
        self.GetBooking = channel.unary_unary(
                '/booking.BookingService/GetBooking',
                request_serializer=booking__pb2.GetBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.Booking.FromString,
                _registered_method=True)
        self.UpdateBooking = channel.unary_unary(
                '/booking.BookingService/UpdateBooking',
                request_serializer=booking__pb2.UpdateBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.Booking.FromString,
                _registered_method=True)
        self.CancelBooking = channel.unary_unary(
                '/booking.BookingService/CancelBooking',
                request_serializer=booking__pb2.CancelBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.CancelBookingResponse.FromString,
                _registered_method=True)
        self.Getings = channel.unary_unary(
                '/booking.BookingService/GetUserBookings',
                request_serializer=booking__pb2.GetUserBookingsRequest.SerializeToString,
                response_deserializer=booking__pb2.BookingList.FromString,
                _registered_method=True)
        self.GetBarberBookings = channel.unary_unary(
                '/booking.BookingService/GetBarberBookings',
                request_serializer=booking__pb2.GetBarberBookingsRequest.SerializeToString,
                response_deserializer=booking__pb2.BookingList.FromString,
                _registered_method=True)
        self.GetAvailableTimeSlots = channel.unary_unary(
                '/booking.BookingService/GetAvailableTimeSlots',
                request_serializer=booking__pb2.GetAvailableTimeSlotsRequest.SerializeToString,
                response_deserializer=booking__pb2.TimeSlotList.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBooking(self, request, context):
        """Create a new booking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooking(self, request, context):
        """Get a specific booking by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBooking(self, request, context):
        """Update an existing booking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBooking(self, request, context):
        """Cancel a booking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserBookings(self, request, context):
        """Get all bookings for a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBarberBookings(self, request, context):
        """Get all bookings for a barber
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableTimeSlots(self, request, context):
        """Get available time slots for a barber on a specific date
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBooking,
                    request_deserializer=booking__pb2.CreateBookingRequest.FromString,
                    response_serializer=booking__pb2.Booking.SerializeToString,
            ),
            'GetBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooking,
                    request_deserializer=booking__pb2.GetBookingRequest.FromString,
                    response_serializer=booking__pb2.Booking.SerializeToString,
            ),
            'UpdateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBooking,
                    request_deserializer=booking__pb2.UpdateBookingRequest.FromString,
                    response_serializer=booking__pb2.Booking.SerializeToString,
            ),
            'CancelBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBooking,
                    request_deserializer=booking__pb2.CancelBookingRequest.FromString,
                    response_serializer=booking__pb2.CancelBookingResponse.SerializeToString,
            ),
            'GetUserBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserBookings,
                    request_deserializer=booking__pb2.GetUserBookingsRequest.FromString,
                    response_serializer=booking__pb2.BookingList.SerializeToString,
            ),
            'GetBarberBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBarberBookings,
                    request_deserializer=booking__pb2.GetBarberBookingsRequest.FromString,
                    response_serializer=booking__pb2.BookingList.SerializeToString,
            ),
            'GetAvailableTimeSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableTimeSlots,
                    request_deserializer=booking__pb2.GetAvailableTimeSlotsRequest.FromString,
                    response_serializer=booking__pb2.TimeSlotList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'booking.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('booking.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/CreateBooking',
            booking__pb2.CreateBookingRequest.SerializeToString,
            booking__pb2.Booking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/GetBooking',
            booking__pb2.GetBookingRequest.SerializeToString,
            booking__pb2.Booking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/UpdateBooking',
            booking__pb2.UpdateBookingRequest.SerializeToString,
            booking__pb2.Booking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/CancelBooking',
            booking__pb2.CancelBookingRequest.SerializeToString,
            booking__pb2.CancelBookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/GetUserBookings',
            booking__pb2.GetUserBookingsRequest.SerializeToString,
            booking__pb2.BookingList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBarberBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/GetBarberBookings',
            booking__pb2.GetBarberBookingsRequest.SerializeToString,
            booking__pb2.BookingList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableTimeSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/booking.BookingService/GetAvailableTimeSlots',
            booking__pb2.GetAvailableTimeSlotsRequest.SerializeToString,
            booking__pb2.TimeSlotList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
